huge changes
The-Codin-Hole/HotWired-Bot pull request #30
Opened 2020-06-12 18:53 UTC by janaSunrise

edit `cogs/fun.py` and `cogs/games.py`
new `assets/`, `cogs/command_utils/`, `cogs/utils/` contains several new file
new embed handler in `cogs/utils/embeds.py`

2020-06-24 08:27 UTC, Faholan commented on assets/context.py
> +        self.message = message
What is the point of creating your own InvokeError ? The library already has one

2020-06-24 08:33 UTC, Faholan commented on cogs/cipher.py
> +            return False
```suggestion
        return self.bot.is_ready():
```

2020-06-24 08:35 UTC, Faholan commented on cogs/cipher.py
> +                      examples=[argument("Hello", "Returns Khoor"), argument("10 Hello", "Returns Rovvy")])
The canonical way of putting a description in a command is with a docstring, not the description kwarg

2020-06-24 08:36 UTC, Faholan commented on cogs/cipher.py
> +                shift = re.findall(f"{pos_neg}\d+", " ".join(shift))[0]
You're doing twice the same exact thing... Make that one

2020-06-24 08:47 UTC, Faholan commented on cogs/cipher.py
> +            message = " ".join(message)
```suggestion
    async def shift(self, ctx, shift: typing.Optional[int], *, message):
        if not shift:
            M = message.split()
            try:
                shift = int(M[-1])
                message = " ".join(M[:-1])
            except ValueError:
                shift = 3
```

2020-06-24 08:49 UTC, Faholan commented on cogs/cipher.py
> +                shift %= -26
```suggestion
        shift %= 26
```
The modulo operation always returns something positive. It's the rest in the Euclidian division

2020-06-24 08:54 UTC, Faholan commented on cogs/cipher.py
> +        sha256_msg = hashlib.sha3_512(message.encode("utf-8")).hexdigest()
If I were you, I'd have used my own SHA

2020-06-24 08:56 UTC, Faholan commented on cogs/cipher.py
> +import cogs.utils.parser as parser
```suggestion
import string

from discord.ext import commands

```
I deleted the part where those two were useful

2020-06-24 09:04 UTC, Faholan commented on cogs/utils/parser.py
> +    if (number*(1000 * pow_ten)) > 1000:
```suggestion
    if pow_ten:
```

2020-06-24 09:08 UTC, Faholan commented on cogs/utils/parser.py
> +    """
```suggestion
    """
    if varient not in [0, 1]:
        raise ValueError(f"varient must be 0 or 1, not {varient}")
```
Or whatever error message you want

2020-06-24 09:10 UTC, Faholan commented on cogs/utils/parser.py
> +        if varient is 1:
```suggestion
        if varient:
```

2020-06-24 09:11 UTC, Faholan commented on cogs/utils/parser.py
> +        return "".join(processed).strip(":")
```suggestion
    if varient:
        return "".join(processed).strip(":")
    else:
        return " ".join(processed)
```
`is` doesn't seem quite right with numbers

2020-07-01 13:20 UTC, Faholan commented on cogs/cipher.py
> +                      description="Flips the alphabet, turns A to Z, B to Y...",
Same : use a docstring

2020-07-01 13:24 UTC, Faholan requested changes
Your thing with `command.help_kwargs` isn't the normal way of doing things
Rather, you should put everything in the docstring, and, for the arguments, override `HelpCommand.get_command_signature`, using the inspecter to retrieve the name and default value (if there is one) of the arguments

2020-07-01 13:25 UTC, Faholan commented on assets/context.py
> +        return fields
All that should be  done in the help command

2020-07-01 13:25 UTC, Faholan commented on assets/context.py
> +        return fields
Same : Help Command

2020-07-01 13:25 UTC, Faholan commented on assets/context.py
> +        self.help_kwargs = {name: value for name, value in kwargs.items() if name in possible_help_kwargs}
This should go in help

2020-07-01 13:27 UTC, Faholan commented on assets/context.py
> +class Command(commands.Command):
Knowing that all the help processing should be done in the help command, subclassing `Command` and `Group` becomes useless

2020-07-01 13:27 UTC, Faholan commented on assets/context.py
> +class Group(commands.Group):
https://github.com/The-Codin-Hole/HotWired-Bot/pull/30/files#r448362046

2020-07-01 13:28 UTC, Faholan commented on cogs/cipher.py
> +                      examples=[argument("Hello", "Returns Khoor"), argument("10 Hello", "Returns Rovvy")])
If you want example, you can put them at the end of the docstring

2020-07-01 13:33 UTC, Faholan commented on cogs/command_utils/games_util.py
> +            return False
R1703 : simplificable-if-statement
```suggestion
        return self.instance and self.current_round <= self.total_rounds
```

2020-07-01 13:34 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        return 3
What is that ?

2020-07-01 13:37 UTC, Faholan commented on assets/context.py
> +import asyncio
D100 / C0114 : Missing docstring in public module

2020-07-01 13:38 UTC, Faholan commented on assets/context.py
> +keyword = namedtuple("keywords", ["keyword", "desc"])
C0103: Class name doesn't conform to PascalCase naming style

translation : Capitalize that

2020-07-01 13:39 UTC, Faholan commented on assets/context.py
> +class Context(commands.Context):
D101 / C0115: Missing docstring in public class

+ don't forget the blank line after the docstring

2020-07-01 13:40 UTC, Faholan commented on assets/context.py
> +    def __init__(self, **kwargs):
D107: Missing dosctring in \_\_init\_\_

2020-07-01 13:40 UTC, Faholan commented on assets/context.py
> +    async def confirm(self, title, content, color=misc.random_color()):
C0116: Missing function or method dosctring

I'm not gonna add all of them : you're missing your docstrings

2020-07-01 13:41 UTC, Faholan commented on assets/context.py
> +    def __init__(self, **kwargs):
+ You don't have a typehint for the return type (Add to all functions)

2020-07-01 13:41 UTC, Faholan commented on assets/context.py
> +    async def confirm_another(self, user, title, content, color=misc.random_color()):
E501: Line too long (85 > 79 characters)

2020-07-01 13:42 UTC, Faholan commented on assets/context.py
> +                return False
Line too long +
R1703: The if statement can be replaced with return test (simplifiable-if-statement)

2020-07-01 13:43 UTC, Faholan commented on assets/context.py
> +            msg = await self.bot.wait_for("message", check=validate_response, timeout=30)
Line too long (all the comments about a line too long will refer to E501)

2020-07-01 13:43 UTC, Faholan commented on assets/context.py
> +        if delete is True:
R1705: Unnecessary "else" after "return" + 
```suggestion
        if delete:
```

2020-07-01 13:44 UTC, Faholan commented on assets/context.py
> +    async def send(self, content=None, *, tts=False, embed=None, file=None, files=None, delete_after=None, nonce=None):
Line too long

2020-07-01 13:44 UTC, Faholan commented on assets/context.py
> +                return
Line too long + R1705: Unnecessary "elif" after "return"

2020-07-01 13:45 UTC, Faholan commented on assets/context.py
> +                return await self.send("I don't have permissions to send embeds!")
Lines too long

2020-07-01 13:45 UTC, Faholan commented on assets/context.py
> +class Command(commands.Command):
Knowing that, Imma skip this class for all formatting errors (missing docstrings, lines too longs...)

2020-07-01 13:46 UTC, Faholan commented on assets/context.py
> +class Group(commands.Group):
Same : skipping formatting comments

2020-07-01 13:47 UTC, Faholan commented on cogs/cipher.py
> +        return self.bot.is_ready():
SYNTAX ERROR

2020-07-01 13:48 UTC, Faholan commented on cogs/cipher.py
> +import base64
D100 / C0114: missing module docstring

2020-07-01 13:49 UTC, Faholan commented on cogs/cipher.py
> +class Ciphers(commands.Cog):
D101 / C0115 : Missing class dosctrings (+ C0116: all methods docstrings)

2020-07-01 13:50 UTC, Faholan commented on cogs/cipher.py
> +    async def cog_check(self, ctx):
WO0236 : Method "cog_check" was expected to be non-async, found it instead as async (invalid-overriden-method)

2020-07-01 13:50 UTC, Faholan commented on cogs/cipher.py
> +                          usage_info("", "If a shift value is not found at the start "
Lines too long, of course, in addition to it not being written the canonical way

2020-07-01 13:51 UTC, Faholan commented on cogs/cipher.py
> +    async def shift(self, ctx, shift: typing.Optional[int], *, message):
F821 / E0602: Undefined variable "typing"

2020-07-01 13:51 UTC, Faholan commented on cogs/cipher.py
> +        # If the shift is higher than 25 then this would convert the shift to a value that is lower than 25
Too long

2020-07-01 13:51 UTC, Faholan commented on cogs/cipher.py
> +        translation_rules = str.maketrans("".join(self.character_set), "".join(shifted_characters))
Too long

2020-07-01 13:52 UTC, Faholan commented on cogs/cipher.py
> +                      description="Flips the alphabet, turns A to Z, B to Y...",
+ Too long (80 > 79 characters)

2020-07-01 13:52 UTC, Faholan commented on cogs/cipher.py
> +        translation_rules = str.maketrans("".join(self.character_set), "".join(reversed_characters))
Too long

2020-07-01 13:52 UTC, Faholan commented on cogs/cipher.py
> +                                         "codepoint to base64 for each letter in the message")
Too long

2020-07-01 13:52 UTC, Faholan commented on cogs/cipher.py
> +                                         "codepoint to base64 for each letter in the message")
Too long

2020-07-01 13:53 UTC, Faholan commented on cogs/cipher.py
> +        """Decodes a message in base64
D205: 1 blank line requierd between summary line and description (found 0)
D400: First line should end with a period (not '4')
D401: First line should be in imperative mood (perhaps 'Decode', not 'Decodes')

2020-07-01 13:54 UTC, Faholan commented on cogs/cipher.py
> +            normal_text = base64.b64decode(message.encode("utf-8")).decode("utf-8")
Too long

2020-07-01 13:54 UTC, Faholan commented on cogs/cipher.py
> +                      example=[example("hello", "Returns 3338be694f50c5f338814986cdf0686453a888b84f424d792af4b9202398f392")])
Too long

2020-07-01 13:54 UTC, Faholan commented on cogs/cipher.py
> +                                           "eb6df891d75f72d9b154518c1cd58835286d1da9a38deba3de98b5a53e5ed78a84976")
Too long

2020-07-01 13:55 UTC, Faholan commented on cogs/cipher.py
> +def setup(bot):
D103 / C0116: Missing dosctring in public function

2020-07-01 13:59 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        super().__init__(ctx, content, color=discord.Color.default(), title="Placeholder Title")
Too long

2020-07-01 13:59 UTC, Faholan commented on cogs/command_utils/games_util.py
> +                                 f"{self.win_lose[0]} wins | {self.win_lose[1]} losses")
Too long

2020-07-01 13:59 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        return str(player_one).translate(conversion), str(player_two).translate(conversion)
Too long

2020-07-01 14:00 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        super().__init__(ctx, content, color=discord.Color.default(), title="Placeholder Title")
Too long

2020-07-01 14:00 UTC, Faholan commented on cogs/command_utils/games_util.py
> +                                 f"{self.win_lose[0]} wins | {self.win_lose[1]} losses")
Too long

2020-07-01 14:01 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        if (bot_choice % 3) + 1 == player_choice:
R1705: Unnecessary "elif" after "return"

2020-07-01 14:02 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        self.controller = self.embed_controller(create=True)
W0201: Attribute 'controller' defined outside \_\_init\_\_

2020-07-01 14:02 UTC, Faholan commented on cogs/command_utils/games_util.py
> +            self.controller_task = self.ctx.bot.loop.create_task(self.controller)
W0201: Attribute 'controller' defined outside \_\_init\_\_

2020-07-01 14:02 UTC, Faholan commented on cogs/command_utils/games_util.py
> +            self.controller_task = self.ctx.bot.loop.create_task(self.controller)
+ too long

2020-07-01 14:04 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        if len([null for null in self.player_responses.values() if null is not None]) != len(self.players.values()):
R1705: Unnecessary "else" after "return" + E501: line too long

2020-07-01 14:05 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        if len([null for null in self.player_responses.values() if null is not None]) != len(self.players.values()):
Simplificable if statement

2020-07-01 14:05 UTC, Faholan commented on cogs/command_utils/games_util.py
> +                return 0
Same as just before

2020-07-01 14:06 UTC, Faholan commented on cogs/command_utils/games_util.py
> +            return True, f"{plys[0]}'s {player_one_words} beats {plys[1]}'s {player_two_words}"
F632 use ==/!= to compare constant literals (str, bytes, int, float, tuple)
R1705: Unnecessary "elif" after "return"

2020-07-01 14:07 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        elif result is 1:
F632 use ==/!= to compare constant literals (str, bytes, int, float, tuple)

2020-07-01 14:08 UTC, Faholan commented on cogs/command_utils/games_util.py
> +    def invoker(self, reaction):
C0116: Missing Function or method dosctring
R1710: Either all return statements in a function should return an expression, or none of them should

2020-07-01 14:09 UTC, Faholan commented on cogs/command_utils/games_util.py
> +           str(reaction.emoji) == "\N{BLACK SQUARE FOR STOP}"):
C0330: Wrong continued indentation before block

2020-07-01 14:09 UTC, Faholan commented on cogs/command_utils/games_util.py
> +            self.control_function = self.stop
W0201: Attribute 'control_function' defined outside \_\_init\_\_

2020-07-01 14:10 UTC, Faholan commented on cogs/command_utils/games_util.py
> +            reaction.message_id != self.peek_player().message.id
C0330: Wrong continued indentation before block (add 4 spaces)

2020-07-01 14:10 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        ):
E124: Closing bracket does not match visual indentation

2020-07-01 14:11 UTC, Faholan commented on cogs/command_utils/games_util.py
> +                self.control_function = functionality
W0201: Attribute 'control_function' defined outside \_\_init\_\_

2020-07-01 14:11 UTC, Faholan commented on cogs/command_utils/games_util.py
> +        self.instance = False
W0201: Attribute 'instance' defined outside \_\_init\_\_

2020-07-01 14:12 UTC, Faholan commented on cogs/command_utils/games_util.py
> +            if await self.ensure_responses(await self.control_function()) is True and self.instance:
Do not use "is True"

2020-07-01 14:15 UTC, Faholan commented on cogs/fun.py
> +        fact = await self.aiohttp_request(link, headers=None)
E1101: Instance of 'Fun' has no 'aiohttp_request' member

2020-07-01 14:16 UTC, Faholan commented on cogs/fun.py
> +        fact = json.loads(fact)
F821 / E0602: Undefined variable 'json'

2020-07-01 14:16 UTC, Faholan commented on cogs/fun.py
> +        fact = await self.aiohttp_request(link, headers=None)
Repeat that comment everywhere you got this

2020-07-01 14:16 UTC, Faholan commented on cogs/fun.py
> +        fact = json.loads(fact)
Repeatable

2020-07-01 14:18 UTC, Faholan commented on cogs/fun.py
> +        """Chooses a random item out of a list for you!
D205: 1 blank line required between summary line and description (found à)
D400: First line should end with a period (not '!')
First line of dosctring should be in imperative mood

2020-07-01 14:18 UTC, Faholan commented on cogs/fun.py
> +        message = re.split(", |,| ", message)
F821 / E0602: Undefined variable 're'

2020-07-01 14:20 UTC, Faholan commented on cogs/games.py
> +from typing import Union
C0411: Standard import "from typing import Union" should be placed before "import discord"

2020-07-01 14:21 UTC, Faholan commented on cogs/games.py
Line 29 and so one :
C0330: Wrong hanging indentation (remove 4 spaces)

2020-07-01 14:22 UTC, Faholan commented on cogs/games.py
>  def setup(client):
there it should be named bot...

2020-07-01 14:23 UTC, Faholan commented on cogs/utils/check.py
> +        return True
R1705
Simplifiable if

2020-07-01 14:24 UTC, Faholan commented on cogs/utils/check.py
> +        return True
R1705
Simplifiable if

2020-07-01 14:24 UTC, Faholan commented on cogs/utils/check.py
> +        return True
R1705
Simplifiable if

2020-07-01 14:26 UTC, Faholan commented on cogs/utils/embeds.py
> +                 title="This is my Game", footer=None, thumbnail=None, image=None):
W0613: Unused argument 'footer'
W0613: Unused argument 'thumbnail'
W0613: Unused argument 'image'
Too long

2020-07-01 14:26 UTC, Faholan commented on cogs/utils/embeds.py
> +                self.control_function = functionality
W0201: Attribute "control_function" defined outside \_\_init\_\_

2020-07-01 14:27 UTC, Faholan commented on cogs/utils/embeds.py
> +    async def stop(self, *args):
W0613: Unused argument *args

2020-07-01 14:28 UTC, Faholan commented on cogs/utils/embeds.py
> +        if get_page and check(get_page[0].content) is 1:
F632: Use ==/!= to compare constant literals (str, bytes, int, float, tuple)

2020-07-01 14:29 UTC, Faholan commented on cogs/utils/embeds.py
> +    async def no(self):
C0103: Method name "no" doesn't conform to snake_case naming style

2020-07-01 14:32 UTC, Faholan commented on cogs/utils/misc.py
> +    ph = PasswordHasher()
C0103: Variable name "ph" doesn't conform to snake_case naming style

2020-07-01 14:32 UTC, Faholan commented on cogs/utils/misc.py
> +    except Exception as e:
Same as for ph, but with e

2020-07-01 14:35 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +                almost_final_spans.append(low), almost_final_spans.append(high)
One instruction per line

2020-07-01 14:35 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +            spans.append(start), spans.append(end)
One instruction per line

2020-07-01 14:35 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +            for m in matches:
C0103: snake_case

2020-07-01 14:36 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +                if detection_results[1] is 1:
F632

2020-07-01 14:36 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +                elif detection_results[1] is 2:
F632

2020-07-01 14:37 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +            if len(match) > 1 and not skip_regex_checks:
R1705: Unnecessary "elif" after return

2020-07-01 14:37 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +                for m in match:
C0103: snake_case

2020-07-01 14:38 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +        return False
Quite a few F632 (is) + R1705 (elif after return)

2020-07-01 14:38 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +            if len(message) % 2 is 0:
F632

2020-07-01 14:39 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +            return result
If result + R1705

2020-07-01 14:39 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +                    return await self.search_variant_cl(ctx, all_parsed_times)
R1705: elif after return

2020-07-01 14:40 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +            if await self.validate(dp_result):
R1705

2020-07-01 14:40 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +        for index, time in enumerate(time_list):
W0612: Unused variable `index`

2020-07-01 14:41 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +                    pass
```suggestion
```
Completely useless

2020-07-01 14:41 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +                return dt, (dt_string[:start] + dt_string[end+1:])
C0103: snake_case on dt

2020-07-01 14:42 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +        except Exception as e:
C0103: snake_case

2020-07-01 14:42 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +        elif self.check is 1:
Two F632

2020-07-01 14:42 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +            if len(message) % 2 is 0:
F632

2020-07-01 14:43 UTC, Faholan commented on cogs/utils/nlp_dates.py
> +        if result is False:
R1705 + Use `if result`

2020-07-01 14:45 UTC, Faholan commented on cogs/utils/parser.py
> +    if not username and ctx:
R1705: unnecessary "elif"

2020-07-01 14:46 UTC, Faholan commented on cogs/utils/parser.py
> +        return False
```suggestion
    return role if isinstance(role, discord.Role) else False
```

2020-07-01 14:46 UTC, Faholan commented on cogs/utils/parser.py
> +    if pow_ten:
R1705

2020-07-01 14:47 UTC, Faholan commented on cogs/utils/parser.py
> +        return [message[0], message[-1]]
Don't use is True or is False + R1705

2020-07-01 14:48 UTC, Faholan commented on cogs/utils/parser.py
> +    """Converts a datetime object to a human readable version
All the comments on dosctring formatting

2020-07-01 14:48 UTC, Faholan commented on cogs/utils/parser.py
> +    unit_list = ["y", "mo", "d", "h", "m", "s"] if varient is 0 else [":"] * 6
F632 NO IS

2020-07-01 14:49 UTC, Faholan commented on cogs/utils/parser.py
> +            if len([quan for quan in processed if quan != 0]) > 2:
R1724: Unnecessary "elif" after "continue"

2020-07-01 14:49 UTC, Faholan commented on cogs/utils/parser.py
> +            elif time_quanity is 0 and (show_all == 2 and id_index in [0, 1, 2, 3]):
F632

2020-07-01 14:49 UTC, Faholan commented on cogs/utils/parser.py
> +        if not show_all and time_quanity is 0:
F632

2020-07-01 14:49 UTC, Faholan commented on cogs/utils/parser.py
> +        return "".join(processed).strip(":")
F632: I was right

2020-07-01 14:51 UTC, Faholan requested changes
Add dosctrings
Shorten your lines
Stop using is
Respect snake_case
Stop putting elif after return

2020-07-13 16:04 UTC, ItsDrike commented
Author of this PR ( @janaSunrise ) either needs to address all requested changes and merge master into this branch to get it up to date with the current code in the repository or this PR will be closed due to inactivity from authors side.

2020-07-16 18:01 UTC, ItsDrike commented
I'm closing this PR due to the long term lack of responses to changes and comments from its author.

2020-07-16 18:01 UTC, closed without merging