Add Verification
The-Codin-Hole/HotWired-Bot pull request #77
Opened 2020-07-07 19:19 UTC by janaSunrise

2020-07-13 14:43 UTC, ItsDrike requested changes

2020-07-13 14:43 UTC, ItsDrike commented on Pipfile
> +pre-commit = "*"
Unacceptable, pre-commit is in `[dev-packages]` there is absolutely no reason to include it in `[packages]`

2020-07-13 14:43 UTC, ItsDrike commented on cogs/verification.py
> +)
Consider using a better import structure:
```suggestion
from discord.ext.commands import (Bot, Cog, CommandInvokeError, Context,
                                  command, has_permissions)
```

2020-07-13 14:43 UTC, ItsDrike commented on cogs/verification.py
> +            self.verify.use_count = 1
This seems irrelevant, keeping track of verification should be done on a per-server basis, not on bot-basis and will be done with database (possibly by API)

2020-07-13 14:43 UTC, ItsDrike commented on cogs/verification.py
> +        if self.verify.use_count % self.word_list_refresh_rate == 1:
Simply use random to determine change. (Generate a simple random number, check the modulo == 0: is divisible) it's pretty non-standard to check modulo (remainder) is 1, instead, we should check 0 equality (divisibility)

2020-07-22 18:57 UTC, ActuallyDaneel reviewed
honestly Drike has said everything there is to say.

2020-08-23 06:07 UTC, merged