Added NSFW Commands from yumenetwork/Yume-Bot
The-Codin-Hole/HotWired-Bot pull request #93
Opened 2020-07-21 20:23 UTC by GrandMoff100

2020-07-21 20:26 UTC, GrandMoff100 commented
Doesn't contain docstrings.

2020-07-22 10:25 UTC, janaSunrise requested changes
Please request those changes, and edit the files to use proper naming convention, and try to make it different, so it clearer

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +    return em
```suggestion
    embed = discord.Embed(color=discord.Colour.red())
    embed.title = provider + " requested by " + author.name
    embed.set_image(url=img)
    return embed
```

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +        return em
```suggestion
        req = requests.get(base + url)
        req = req.json()
        embed = await make_embed(req['data']['response']["url"], "Nekos.life", author)
        return embed
```

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +            msg: discord.Message = await ctx.send(embed=em)
```suggestion
            embed = await self.get(source, ctx.author)
            msg = await ctx.send(embed=embed)
```

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +            await msg.add_reaction("😻")
```suggestion
```

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +        await msg.add_reaction("😻")
```suggestion
        embed = await self.get(source, ctx.author)
        msg = await ctx.send(embed=embed)
```

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +            await msg.add_reaction("❤️")
```suggestion
            embed = await self.get(source, ctx.author)
            msg = await ctx.send(embed=embed)
```

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +            await msg.add_reaction("❤️")
```suggestion
    @neko.command(name="kitsune")
    @commands.guild_only()
    async def sfw_kitsune(self, ctx):
        async with ctx.typing():
            source = "images/sfw/img/kitsune"
            embed = await self.get(source, ctx.author)
            msg = await ctx.send(embed=embed)
```

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +        await msg.add_reaction("😻")
```suggestion
        embed = await self.get(source, ctx.author)
        msg = await ctx.send(embed=embed)
```

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +        await msg.add_reaction("❤️")
```suggestion
        embed = await self.get(source, ctx.author)
        msg = await ctx.send(embed=embed)
```

2020-07-22 10:25 UTC, janaSunrise commented on bot/cogs/nsfw/neko.py
> +        await msg.add_reaction("❤️")
```suggestion
        embed = await self.get(source, ctx.author)
        msg = await ctx.send(embed=embed)
```

2020-07-23 11:02 UTC, ItsDrike requested changes
While I've requested some changes to code itself isn't that bad, although I do want to state my position on this which is that I'm personally not a huge fan of having NSFW commands like this in the bot and after these changes will get resolved I won't approve this PR because of that if it will get 2 approvals anyway, it can be merged even though I'm personally against having this in our bot.

2020-07-23 12:17 UTC, janaSunrise commented on bot/cogs/reddit.py
> -        pass
i got this error from flake8-bear

2020-07-23 20:38 UTC, ItsDrike commented on bot/cogs/reddit.py
> -        pass
Can you show me the specific error number with corresponding message to it?

2020-08-05 09:38 UTC, merged